import { NextResponse } from 'next/server';
import { createClient } from '@/utils/supabase/server';
import OpenAI from 'openai';



export async function POST(request: Request) {
  try {
    const { language, focus } = await request.json();
    const supabase = await createClient();

    // Verify authentication
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    if (!process.env.GEMINI_API_KEY) {
      return NextResponse.json({ error: 'Gemini API key missing in environment variables' }, { status: 500 });
    }
    if (!process.env.SUPABASE_SERVICE_ROLE_KEY) {
      return NextResponse.json({ error: 'Supabase Service Role Key missing in environment variables' }, { status: 500 });
    }

    const { GoogleGenAI } = require('@google/genai');
    const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
    
    const prompt = `
      You are an expert technical interviewer. Generate a Leetcode-style algorithmic coding challenge.
      The candidate's primary language is ${language || 'JavaScript'}.
      ${focus ? `CRITICAL REQUIREMENT: The candidate needs to improve in the following specific areas: ${focus}. Create a question that specifically tests these concepts.` : ''}
      
      Requirements:
      1. The question should be challenging but solvable in 15-30 minutes.
      2. It should test core algorithmic concepts (arrays, strings, hash maps, pointers, etc.).
      3. Provide a clear title, description with examples, and 2 exact test cases.
    `;

    const response = await ai.models.generateContent({
        model: 'gemini-3.6-flash',
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            systemInstruction: `Respond strictly in the following JSON format:
            {
              "title": "String",
              "description": "String (Include problem statement and examples)",
              "language": "String (lowercase, e.g. javascript, python, typescript)",
              "test_cases": [
                { "input": "String", "expected_output": "String" },
                { "input": "String", "expected_output": "String" }
              ]
            }`
        }
    });

    const content = response.text;
    if (!content) throw new Error("No content generated by Gemini");
    
    const parsedQuestion = JSON.parse(content);
    
    // Create an admin client to bypass RLS for inserting system-generated questions
    const { createClient: createSupabaseClient } = require('@supabase/supabase-js');
    const supabaseAdmin = createSupabaseClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL,
      process.env.SUPABASE_SERVICE_ROLE_KEY
    );

    // Insert into Supabase using admin client
    const { data: newQuestion, error } = await supabaseAdmin.from('questions').insert({
      title: parsedQuestion.title,
      description: parsedQuestion.description,
      language: parsedQuestion.language.toLowerCase(),
      test_cases: parsedQuestion.test_cases,
    }).select().single();

    if (error) {
      console.error('Database Error:', error);
      return NextResponse.json({ error: 'Failed to save question to database: ' + error.message }, { status: 500 });
    }

    return NextResponse.json({ question: newQuestion });

  } catch (error: any) {
    console.error('AI Generation Error:', error);
    return NextResponse.json({ error: error.message || 'Failed to generate assessment' }, { status: 500 });
  }
}
